# Generated by Django 2.0.4 on 2018-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='50 characters max', max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('comment', models.TextField(default='messages sent')),
            ],
        ),
    ]
