# Generated by Django 2.0.4 on 2018-06-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('album_name', models.CharField(max_length=50, null=True)),
                ('song_title', models.CharField(max_length=50)),
                ('file_name', models.FileField(upload_to='audios_files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('album_name', models.CharField(max_length=50, null=True)),
                ('song_title', models.CharField(max_length=50)),
                ('file_name', models.FileField(upload_to='video_files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='musicanmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='addsmodel',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='selection',
        ),
        migrations.AddField(
            model_name='addsmodel',
            name='image_name',
            field=models.ImageField(default='images', upload_to='adds_picture_files'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='image_name',
            field=models.ImageField(default='images', upload_to='gallery_files'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='picture_files'),
        ),
        migrations.DeleteModel(
            name='MusicanModel',
        ),
    ]
