# Generated by Django 2.0.4 on 2018-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20180613_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='addsmodel',
            name='image_name',
            field=models.ImageField(default='images', upload_to='adds_picture_files/'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image_name',
            field=models.ImageField(default='images', upload_to='gallery_files/'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='picture_files/'),
        ),
    ]
