# Generated by Django 2.0.4 on 2018-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20180613_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsmodel',
            name='image_name',
            field=models.FileField(default='images', upload_to='adds_picture_files/'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image_name',
            field=models.FileField(default='images', upload_to='gallery_files/'),
        ),
    ]
