# Generated by Django 2.0.4 on 2018-06-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20180613_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='file_name',
            field=models.FileField(upload_to='audios_files/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='file_name',
            field=models.FileField(upload_to='video_files/'),
        ),
    ]
