# Generated by Django 2.0.4 on 2018-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20180614_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsmodel',
            name='image_name',
            field=models.ImageField(blank=True, upload_to='adds_picture_files/'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image_name',
            field=models.ImageField(blank=True, upload_to='gallery_files/'),
        ),
    ]
