# Generated by Django 2.0.4 on 2018-06-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_auto_20180616_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='audiomodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='user_id',
        ),
    ]
